backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Homepage"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "Hero Subtitle", name: "hero_subtitle", widget: "text" }
          - { label: "Hero Button Text", name: "hero_button_text", widget: "string", default: "Visit Facebook Page" }
          - { label: "Hero Button Link", name: "hero_button_link", widget: "string", default: "https://web.facebook.com/AmbeeConcepts/" }
