backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Website Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "index.html"
        fields:
          - {label: "Hero Title", name: "hero_title", widget: "string"}
